apiVersion: v1
data:
  CLIENT_ID: data-proxy-server
  DEBUG: "False"
  FLASK_APP: run.py
  FLASK_ENV: production
  INFLUXDB_ADDRESS: "your-influxdb-address"
  INFLUXDB_BUCKET: your-bucket
  INFLUXDB_ORG: your-org
  MQTT_BROKER_ADDRESS: rebus.ninja
  MQTT_BROKER_PORT: "1883"
  APP_DATA_PATH: /app/data
  WEATHER_API_URL: "http://api.openweathermap.org/data/2.5/weather?"
  DATA_PROXY_URL: "http://192.168.1.153:5000"
  DATA_ANALYSIS_SERVER_URL: "http://192.168.1.153:5010"
kind: ConfigMap
metadata:
  name: data-proxy-config
  namespace: iot
---
apiVersion: v1
kind: Secret
metadata:
  name: data-proxy-secret
  namespace: iot
type: Opaque
data:
  mqtt-username: your-user-base64
  mqtt-password: your-password-base64
  influxdb-token: your-influxdb-token-base64
  openweather-api-key: your-openweather-api-key-base64
  telegram-bot-token: your-telegram-bot-token-base64