apiVersion: v1
kind: ConfigMap
metadata:
  name: data-proxy-config
  namespace: iot
data: 
  env: |
    # Flask settings
    DEBUG=False
    FLASK_APP=run.py
    FLASK_ENV=production

    # MQTT settings
    MQTT_BROKER_ADDRESS=your-mqtt-broker.com
    MQTT_BROKER_PORT=1883
    CLIENT_ID=data-proxy-server

    # InfluxDB settings
    INFLUXDB_ADDRESS=your-influxdb-server.com
    INFLUXDB_ORG=your-influxdb-org
    INFLUXDB_BUCKET=your-influxdb-bucket
---
# secret for MQTT credentials and InfluxDB token
apiVersion: v1
kind: Secret
metadata:
  name: data-proxy-secret
  namespace: iot
type: Opaque
data:
  mqtt-username: your-mqtt-user
  mqtt-password: your-mqtt-pass
  influxdb-token: your-influxdb-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-proxy-server
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-proxy-server
  template:
    metadata:
      labels:
        app: data-proxy-server
    spec:
      containers:
      - name: data-proxy-server
        image: unibo-iot/python-data-proxy-server:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-proxy-config
          mountPath: /app
        env:
        - name: MQTT_USERNAME
          valueFrom:
            secretKeyRef:
              name: data-proxy-secret
              key: mqtt-username
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-proxy-secret
              key: mqtt-password
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: data-proxy-secret
              key: influxdb-token
      volumes:
      - name: data-proxy-config
        configMap:
          name: data-proxy-config
          items:
          - key: env
            path: .env