apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-analysis-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/iot/data-analysis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-analysis-pvc
  namespace: iot
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analysis-server
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-analysis-server
  template:
    metadata:
      labels:
        app: data-analysis-server
    spec:
      volumes:
        - name: data-analysis-volume
          persistentVolumeClaim:
            claimName: data-analysis-pvc
      containers:
      - name: data-analysis-server
        image: docker.io/unibo-iot/python-data-analysis-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: data-analysis-config
        env:
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: data-analysis-secret
              key: influxdb-token
        volumeMounts:
        - name: data-analysis-volume
          mountPath: /data_analysis/data
---
apiVersion: v1
kind: Service
metadata:
  name: data-analysis-service
  namespace: iot
  annotations:
    metallb.universe.tf/allow-shared-ip: iot
    metallb.universe.tf/ip-allocated-from-pool: first-pool
spec:
  selector:
    app: data-analysis-server
  ports:
    - port: 5010
      targetPort: 8000
  type: LoadBalancer