apiVersion: v1
data:
  CLIENT_ID: data-proxy-server
  DEBUG: "False"
  FLASK_APP: run.py
  FLASK_ENV: production
  INFLUXDB_ADDRESS: "your-influxdb-address"
  INFLUXDB_BUCKET: your-bucket
  INFLUXDB_ORG: your-org
  MQTT_BROKER_ADDRESS: rebus.ninja
  MQTT_BROKER_PORT: "1883"
  APP_DATA_PATH: /app/data
kind: ConfigMap
metadata:
  name: data-proxy-config
  namespace: iot
---
apiVersion: v1
kind: Secret
metadata:
  name: data-proxy-secret
  namespace: iot
type: Opaque
data:
  mqtt-username: your-user-base64
  mqtt-password: your-password-base64
  influxdb-token: your-influxdb-token-base64